// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0oO4RXdaOlpkvWOPjXyZquAvUS6SZpxg',
    appId: '1:847446101407:web:88da59cb742081ac7541aa',
    messagingSenderId: '847446101407',
    projectId: 'flutter-udemy-48517',
    authDomain: 'flutter-udemy-48517.firebaseapp.com',
    databaseURL: 'https://flutter-udemy-48517-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-udemy-48517.appspot.com',
    measurementId: 'G-CX72V0NQE5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSHmmN0_fo3_hvhI0wBa0t0sRCfBHYDqM',
    appId: '1:847446101407:android:3c2ad0f76eed27037541aa',
    messagingSenderId: '847446101407',
    projectId: 'flutter-udemy-48517',
    databaseURL: 'https://flutter-udemy-48517-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-udemy-48517.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwMqWu2U2boOdvePixIWMlU3S-xTgX2X8',
    appId: '1:847446101407:ios:a671090ad9e305087541aa',
    messagingSenderId: '847446101407',
    projectId: 'flutter-udemy-48517',
    databaseURL: 'https://flutter-udemy-48517-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-udemy-48517.appspot.com',
    iosClientId: '847446101407-li913or7nbkg6krcnorgss111t4opt6a.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwMqWu2U2boOdvePixIWMlU3S-xTgX2X8',
    appId: '1:847446101407:ios:a671090ad9e305087541aa',
    messagingSenderId: '847446101407',
    projectId: 'flutter-udemy-48517',
    databaseURL: 'https://flutter-udemy-48517-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-udemy-48517.appspot.com',
    iosClientId: '847446101407-li913or7nbkg6krcnorgss111t4opt6a.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
